apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: gilles
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp # Nom pour le port AMQP (5672)
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management # Nom pour le port de gestion (15672)
      protocol: TCP
      port: 15672
      targetPort: 15672
