apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: gilles
spec:
  selector:
    app: backend
  ports:
    - name: http-backend
      port: 5000 
      targetPort: 5000 
  type: ClusterIP 
